# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    ignore:
      # TODO: Fix incompatibilities with AG Grid 29
      - dependency-name: "ag-grid-community"
        versions: ["29.x"]
      - dependency-name: "ag-grid-react"
        versions: ["29.x"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
